### ISSUE TITLE
Building uses system libraries

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/freetype2#1]
Using the build instructions in the README I see the following when running the Makefile:
```
./builds/unix/libtool --mode=compile psp-gcc -pedantic -ansi -I/home/wouter/Sources/psplibraries/freetype2/src/freetype2-2.10.2-psp/objs -I./builds/unix -I/home/wouter/Sources/psplibraries/freetype2/src/freetype2-2.10.2-psp/include  -c -Wall -G0 -g -O2 -fvisibility=hidden  -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DFT_CONFIG_CONFIG_H="<ftconfig.h>" -DFT_CONFIG_MODULES_H="<ftmodule.h>" -DFT_CONFIG_OPTIONS_H="<ftoption.h>" -DFT2_BUILD_LIBRARY -o /home/wouter/Sources/psplibraries/freetype2/src/freetype2-2.10.2-psp/objs/ftsystem.lo /home/wouter/Sources/psplibraries/freetype2/src/freetype2-2.10.2-psp/src/base/ftsystem.c
```
It seems the system's harfbuzz, glib and libpng are being used. Full log [here](https://gist.github.com/sharkwouter/99e90b69a20d86010d0e300c8cc67323).

I'm building from this PSPBUILD:
```
# Maintainer: Wouter Wijsman <wwijsman@live.nl>
pkgname=freetype2
pkgver=2.10.2
pkgrel=1
pkgdesc="OpenGL-ESish library for PSP"
arch=('mips')
url="https://github.com/pspdev/psp-ports"
license=('custom:Freetype' 'GPL2')
depends=('zlib')
makedepends=()
optdepends=()
provides=('freetype')
source=("https://github.com/pspdev/freetype2/archive/${pkgver}-psp.tar.gz")
sha256sums=('SKIP')

build() {
	cd "$pkgname-$pkgver-psp"
	./autogen.sh
	LDFLAGS="-L$(psp-config --pspsdk-path)/lib" LIBS="-lc -lpspuser" \
	./configure --host psp --prefix=/psp
	make
}

package() {
	cd "$pkgname-$pkgver-psp"
	make DESTDIR="$pkgdir/" install

	mkdir -m 755 -p "$pkgdir/psp/share/licenses/$pkgname"
	install -m644 docs/LICENSE.TXT "$pkgdir/psp/share/licenses/$pkgname/LICENSE.TXT"
	install -m644 docs/GPLv2.TXT "$pkgdir/psp/share/licenses/$pkgname/GPLv2.TXT"
	install -m644 docs/FTL.TXT "$pkgdir/psp/share/licenses/$pkgname/FTL.TXT"
}
```

The script in psplibraries uses a slightly different build command as well, but I'm not sure if that's useful:
```
test_deps_install zlib
get_pspport freetype2 freetype2-psp
run_autogen_build --enable-freetype-config \
  --without-bzip2 --without-png
```

**Comment by sharkwouter** [comment]
I found the workaround:
```
unset PKG_CONFIG_PATH
 export PKG_CONFIG_LIBDIR="$(psp-config --psp-prefix)/lib/pkgconfig"
```
This should be added to the makepkg.conf. I'll get on it.

**Comment by carstene1ns** [comment]
https://gist.github.com/sharkwouter/99e90b69a20d86010d0e300c8cc67323#file-gistfile1-txt-L74-L75

I do not want to talk about the same things over and over again. We have talked about this over discord already 2 times.
This "fix" is not needed, since `psp-pkg-config` takes care of it. You are not using it, so your build breaks.

**Comment by sharkwouter** [comment]
I know we did, sorry about that, I just don't really understand how this works. How would I use psp-pkg-config when building without setting this?

**Comment by sharkwouter** [comment]
Anyway, I'll revert the commit

**Comment by carstene1ns** [comment]
When `psp-pkg-config` is in the path, everything works like expected.
autotools will deprecate using host `pkg-config` in the future for cross-compilations, so the warning will be an error by then.

**Comment by sharkwouter** [comment]
Ah, I must've reinstalled the toolchain then, otherwise I would've had it.
